version: '3.8'

services:

  backend:
    build:
      context: .
    container_name: "sc-backend"
    command: python manage.py runserver
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass
    depends_on:
      - database
  
  database:
    image: postgres:15.4-alpine
    container_name: "sc-database"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass
    volumes:
      - sc_pg_data:/var/lib/postgresql/data

volumes:
  sc_pg_data: